// AUTO-GENERATED by scripts/generate-seo-shell.mjs — do not edit.
// Source: dist/index.html (built SPA shell). Regenerated on every build.
export const SEO_SHELL_HTML = `<!doctype html>
<html lang="en" class="dark">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <!-- Primary SEO -->
    <title>PlayBeat Digital — Premium Digital Marketplace & Smart Projectors</title>
    <meta name="description" content="Instant digital keys, gaming accounts, subscriptions, AI tools, SaaS licenses, and high-performance 4K Smart Projectors with 24/7 automated delivery." />
    <meta name="keywords" content="playbeat digital, digital marketplace pakistan, netflix subscription, chatgpt plus, windows 11 key, office 365, steam gift card, xbox game pass, smart 4k projector, magcubic projector, iptv" />
    <meta name="author" content="PlayBeat Digital" />
    <meta name="robots" content="index, follow, max-image-preview:large, max-snippet:-1, max-video-preview:-1" />
    <meta name="googlebot" content="index, follow" />
    <meta name="google-site-verification" content="-USsgNvQV8Ip4Qjj00D5uJra7RFqmKvrFS4RhvKyqRw" />
    <meta name="theme-color" content="#050814" />
    <meta name="format-detection" content="telephone=no" />
    <link rel="canonical" href="https://playbeat.digital/" />

    <!-- PWA / installable web app -->
    <link rel="manifest" href="/manifest.webmanifest" />
    <meta name="mobile-web-app-capable" content="yes" />
    <meta name="application-name" content="PlayBeat Digital" />
    <link rel="apple-touch-icon" sizes="180x180" href="/pwa/apple-touch-icon.png" />
    <meta name="apple-mobile-web-app-capable" content="yes" />
    <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent" />
    <meta name="apple-mobile-web-app-title" content="PlayBeat" />
    <link rel="icon" type="image/png" sizes="48x48" href="/pwa/favicon-48.png" />

    <!-- Open Graph (Facebook / WhatsApp / Telegram link previews) -->
    <meta property="og:type" content="website" />
    <meta property="og:site_name" content="PlayBeat Digital" />
    <meta property="og:url" content="https://playbeat.digital/" />
    <meta property="og:title" content="PlayBeat Digital — Premium Digital Marketplace & Smart Projectors" />
    <meta property="og:description" content="Instant digital keys, gaming accounts, subscriptions, AI tools, SaaS licenses, and high-performance 4K Smart Projectors with 24/7 automated delivery." />
    <meta property="og:image" content="https://playbeat.digital/assets/images/playbeat/hero-marketplace.png" />
    <meta property="og:image:width" content="1200" />
    <meta property="og:image:height" content="630" />
    <meta property="og:image:alt" content="PlayBeat Digital — Premium Digital Marketplace" />
    <meta property="og:locale" content="en_US" />

    <!-- Twitter Card -->
    <meta name="twitter:card" content="summary_large_image" />
    <meta name="twitter:url" content="https://playbeat.digital/" />
    <meta name="twitter:title" content="PlayBeat Digital — Premium Digital Marketplace & Smart Projectors" />
    <meta name="twitter:description" content="Instant digital keys, gaming accounts, subscriptions, AI tools, SaaS licenses, and high-performance 4K Smart Projectors with 24/7 automated delivery." />
    <meta name="twitter:image" content="https://playbeat.digital/assets/images/playbeat/hero-marketplace.png" />

    <!-- Structured data: Organization + WebSite (helps Google index the brand) -->
    <script type="application/ld+json">
    {
      "@context": "https://schema.org",
      "@graph": [
        {
          "@type": "Organization",
          "@id": "https://playbeat.digital/#organization",
          "name": "PlayBeat Digital",
          "url": "https://playbeat.digital/",
          "logo": "https://playbeat.digital/playbeat-logo.png",
          "contactPoint": {
            "@type": "ContactPoint",
            "contactType": "customer support",
            "email": "support@playbeat.digital",
            "availableLanguage": ["English", "Urdu"]
          },
          "address": {
            "@type": "PostalAddress",
            "addressLocality": "Abbottabad",
            "addressRegion": "Khyber Pakhtunkhwa",
            "addressCountry": "PK"
          }
        },
        {
          "@type": "WebSite",
          "@id": "https://playbeat.digital/#website",
          "url": "https://playbeat.digital/",
          "name": "PlayBeat Digital",
          "description": "Premium digital marketplace & smart projectors",
          "publisher": { "@id": "https://playbeat.digital/#organization" },
          "potentialAction": {
            "@type": "SearchAction",
            "target": "https://playbeat.digital/?q={search_term_string}",
            "query-input": "required name=search_term_string"
          }
        }
      ]
    }
    </script>

    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700;800&family=Montserrat:wght@500;600;700;800&family=Unbounded:wght@800;900&family=Playfair+Display:ital,wght@0,400;0,600;0,700;1,400;1,600&family=JetBrains+Mono:wght@400;500;600;700&family=Nunito:wght@300;400;600;700;800;900&family=Plus+Jakarta+Sans:wght@400;500;600;700;800&display=swap" rel="stylesheet" />
    <link rel="icon" type="image/svg+xml" href="/favicon.svg" />

    <!-- Google tag (gtag.js) — GA4 -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=G-5TYLQD0J2N"></script>
    <script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());
      gtag('config', 'G-5TYLQD0J2N');
    </script>

    <!-- Google AdSense (publisher ca-pub-9777611286139666) -->
    <meta name="google-adsense-account" content="ca-pub-9777611286139666" />
    <script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-9777611286139666"
      crossorigin="anonymous"></script>

    <!-- Meta Pixel Code -->
    <script>
    !function(f,b,e,v,n,t,s)
    {if(f.fbq)return;n=f.fbq=function(){n.callMethod?
    n.callMethod.apply(n,arguments):n.queue.push(arguments)};
    if(!f._fbq)f._fbq=n;n.push=n;n.loaded=!0;n.version='2.0';
    n.queue=[];t=b.createElement(e);t.async=!0;
    t.src=v;s=b.getElementsByTagName(e)[0];
    s.parentNode.insertBefore(t,s)}(window, document,'script',
    'https://connect.facebook.net/en_US/fbevents.js');
    fbq('init', '1971402550484565');
    fbq('track', 'PageView');
    </script>
    <!-- End Meta Pixel Code -->
    <script type="module" crossorigin src="/assets/index-C7JYypfv.js"></script>
    <link rel="modulepreload" crossorigin href="/assets/vendor-icons-9LwQIMG3.js">
    <link rel="modulepreload" crossorigin href="/assets/vendor-react-TDEt5WUy.js">
    <link rel="stylesheet" crossorigin href="/assets/index-Cn_x-g5v.css">
  </head>
  <body class="bg-[#0A0A0B] text-[#E0E0E0] antialiased selection:bg-emerald-500 selection:text-black">
    <!-- Meta Pixel Code (noscript fallback) -->
    <noscript><img height="1" width="1" style="display:none"
    src="https://www.facebook.com/tr?id=1971402550484565&ev=PageView&noscript=1"
    /></noscript>
    <!-- End Meta Pixel Code -->
    <div id="root">
      <div style="min-height:100vh;background:#050814;color:#e5e7eb;font-family:Inter,system-ui,-apple-system,Segoe UI,sans-serif;padding:24px 16px;box-sizing:border-box"><div style="max-width:920px;margin:0 auto">
      <h1 style="color:#fff;font-size:26px;line-height:1.25;margin:10px 0 14px;font-weight:800">Premium Digital Marketplace &amp; Smart Projectors</h1>
      <p style="line-height:1.7;color:#c7ccd6;margin:0 0 14px;font-size:15px">Instant digital keys, gaming accounts, subscriptions, AI tools, SaaS licenses, and high-performance 4K Smart Projectors with 24/7 automated delivery.</p>
      <h2 style="color:#fff;font-size:18px;margin:6px 0 10px;font-weight:700">Browse by category</h2>
      <ul style="list-style:disc;padding-left:20px;margin:0 0 14px;color:#c7ccd6">
        <li><a href="/streaming" style="color:#7dd3fc">Streaming</a></li>
        <li><a href="/subscriptions" style="color:#7dd3fc">Subscriptions</a></li>
        <li><a href="/gift-cards" style="color:#7dd3fc">Gift Cards</a></li>
        <li><a href="/gaming" style="color:#7dd3fc">Gaming</a></li>
        <li><a href="/software" style="color:#7dd3fc">Software</a></li>
        <li><a href="/smart-projectors" style="color:#7dd3fc">Smart Projectors</a></li>
        <li><a href="/smart-4k-projectors" style="color:#7dd3fc">Smart 4K Projectors</a></li>
        <li><a href="/ai-subscriptions" style="color:#7dd3fc">AI Subscriptions</a></li>
        <li><a href="/steam-game-keys" style="color:#7dd3fc">Steam &amp; Game Keys</a></li>
        <li><a href="/windows-office" style="color:#7dd3fc">Windows &amp; Office</a></li>
        <li><a href="/creative-software" style="color:#7dd3fc">Creative Software</a></li>
        <li><a href="/digital-services" style="color:#7dd3fc">Digital Services</a></li>
        <li><a href="/social-media" style="color:#7dd3fc">Social Media</a></li>
        <li><a href="/web-hosting" style="color:#7dd3fc">Web Hosting</a></li>
        <li><a href="/digital-marketing" style="color:#7dd3fc">Digital Marketing</a></li>
        <li><a href="/web3" style="color:#7dd3fc">Web3</a></li>
      </ul>
      </div></div></div>
  </body>
</html>
`;
