// generate_product_sitemap.mjs — insert every product's unique slug URL into
// public/sitemap.xml (idempotent: replaces the existing <!-- Products --> block)
import { readFileSync, writeFileSync } from 'node:fs'

const src = readFileSync(new URL('../src/data/products.ts', import.meta.url), 'utf8')
const blocks = src.split(/\{\s*"id":/).slice(1)
const slugs = []
for (const b of blocks) {
  const rawId = (b.trim().match(/^"([^"]+)"/) || [])[1]
  if (!rawId || !/^pb-/i.test(rawId)) continue
  const slug = (b.match(/"slug":\s*"([^"]*)"/) || [])[1]
  if (slug) slugs.push(slug)
}
console.log(`Found ${slugs.length} product slugs`)

// uniqueness guard
const set = new Set(slugs)
if (set.size !== slugs.length) throw new Error('DUPLICATE SLUGS in products.ts — refusing to write sitemap')

const smPath = new URL('../public/sitemap.xml', import.meta.url)
let xml = readFileSync(smPath, 'utf8')
const today = new Date().toISOString().slice(0, 10)

// Drop any previous product block, then append fresh
xml = xml.replace(/\n  <!-- Products \(auto-generated\) -->[\s\S]*?(?=<\/urlset>)/, '\n')
const entries = slugs
  .map(
    (s) => `  <url>
    <loc>https://playbeat.digital/product/${s}</loc>
    <lastmod>${today}</lastmod>
    <changefreq>weekly</changefreq>
    <priority>0.8</priority>
  </url>`
  )
  .join('\n')
xml = xml.replace('</urlset>', `  <!-- Products (auto-generated by scripts/generate_product_sitemap.mjs) -->\n${entries}\n</urlset>`)
writeFileSync(smPath, xml)
console.log(`sitemap.xml now contains ${slugs.length} product URLs`)
