// generate-hero-replica.tsx — perf task §5 (LCP).
//
// Renders the REAL hero surface (HeroSurfaceBridge — announcement bar +
// HeroHeaderStage) to static HTML with the exact initial state the client's
// first render will use, so hydrateRoot() adopts the server nodes
// byte-for-byte (zero mismatch → zero client re-render → LCP stays at the
// early replica paint instead of resetting to React commit time).
//
// Run with BUN (tsx execution):  bun scripts/generate-hero-replica.tsx
// Wired BEFORE generate-seo-shell.mjs in the build (see below). The shell
// generator reads the emitted JSON; if this file's output is missing or
// stale the shell falls back to the legacy simplified replica.
//
// IF YOU EDIT HeroHeaderStage or the announcement bar markup, RE-RUN THIS
// SCRIPT so the replica matches (otherwise hydration recovers by
// re-creating the hero — page still works, LCP improvement is lost).

import { renderToStaticMarkup } from "react-dom/server";
import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import path from "node:path";
import React from "react";
import { HeroSurfaceBridge, setHeroState } from "../src/heroBridge";

// Build-time CMS announcement snapshot. MUST match the live announcement the
// replica represents (same rule/constraint as the previous hand-written
// replica: editing the CMS announcement text requires a rebuild/redeploy).
const ANNOUNCEMENT = {
  enabled: true,
  text: "🔥 Global Best Prices 🌍 | ⚡ Instant Delivery 🚀 | 🔒 Secure Payments 💳 | 🌎 Available Worldwide ✨ | 💎 Trusted Premium Products⭐",
  link: "",
};

// Initial render state — MUST equal the client's first render values:
// visible=true (replica only ships on "/"), user=null (auth resolves later),
// counts=0 (badges only render when > 0), searchQuery=''.
setHeroState({
  visible: true,
  announcement: ANNOUNCEMENT,
  user: null,
  cartCount: 0,
  wishlistCount: 0,
  searchQuery: "",
});

const html = renderToStaticMarkup(React.createElement(HeroSurfaceBridge));

if (!html.includes("pbhs-stage") || !html.includes("pbhs-s")) {
  console.error("[generate-hero-replica] rendered markup is missing expected hero parts — aborting");
  process.exit(1);
}
if (html.includes("<h1")) {
  console.error("[generate-hero-replica] replica must NOT contain the sr-only H1 (deferSrH1) — aborting");
  process.exit(1);
}

const outDir = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const jsonPath = path.join(outDir, "api", "_lib", "heroReplica.generated.json");
const tsPath = path.join(outDir, "api", "_lib", "heroReplica.generated.ts");

writeFileSync(jsonPath, JSON.stringify({ announcement: ANNOUNCEMENT, html }, null, 0));
writeFileSync(
  tsPath,
  "// AUTO-GENERATED by scripts/generate-hero-replica.tsx — do not edit.\n" +
    "// Static hero replica (announcement + stage) for the homepage shell.\n" +
    "export const HERO_REPLICA_HTML = " + JSON.stringify(html) + ";\n" +
    "export const PB_ANNOUNCEMENT_SNAPSHOT = " + JSON.stringify(ANNOUNCEMENT) + ";\n"
);

console.log(`[generate-hero-replica] wrote api/_lib/heroReplica.generated.{json,ts} (${(html.length / 1024).toFixed(1)} KB markup)`);
