/**
 * Scope the SB Admin 2 stylesheet (Bootstrap 4.6 + SB2 customizations)
 * under the admin root class `.pbadmin` so the storefront is untouched.
 *
 * - Every selector gets prefixed: `.foo` → `.pbadmin .foo`
 * - html/body/:root selectors map to `.pbadmin` itself (tokens + font)
 * - Output: src/admin/sb2-scoped.css (imported inside AdminInsightsView)
 *
 * Run: node scripts/scope_sb2.mjs
 */
import postcss from 'postcss'
import prefixer from 'postcss-prefix-selector'
import { readFileSync, writeFileSync, mkdirSync } from 'fs'
import { dirname, resolve } from 'path'
import { fileURLToPath } from 'url'

const __dirname = dirname(fileURLToPath(import.meta.url))
const ROOT = resolve(__dirname, '..')
const IN = process.argv[2] || '/tmp/sb-admin-2.css'
const OUT = resolve(ROOT, 'src/admin/sb2-scoped.css')

const css = readFileSync(IN, 'utf8')

const result = postcss([
  prefixer({
    prefix: '.pbadmin ',
    transform(prefix, selector, prefixedSelector) {
      const s = selector.trim()
      // Root-level selectors: map to the wrapper itself (no descendant space)
      if (/^(html|body|:root)([\s,:[]|$)/.test(s)) {
        // "html", "body", ":root", "html body", ":root[data-x]" → .pbadmin
        return '.pbadmin'
      }
      // Already-prefixed or keyframe selectors pass through
      if (s.startsWith(prefix.trim())) return s
      return prefixedSelector
    },
  }),
]).process(css, { from: IN })

mkdirSync(dirname(OUT), { recursive: true })

// Bootstrap's text utilities carry !important by design; inside the admin
// they would defeat the theme's light-zone text flips (.text-white → ink).
// Bootstrap text-* color utilities are unused by admin markup, so the
// !important is stripped from the two that could ever collide.
const finalCss = result.css
  .replace(/(\.pbadmin \.text-white\s*\{[^}]*?color:\s*#fff)\s*!important\s*;/g, '$1;')
  .replace(/(\.pbadmin \.text-body\s*\{[^}]*?color:[^;}]+)\s*!important\s*;/g, '$1;')

const out = `/* ============================================================
   SB ADMIN 2 v4.1.4 (StartBootstrap) — scoped under .pbadmin
   Generated by scripts/scope_sb2.mjs — DO NOT EDIT BY HAND.
   Bootstrap 4.6 + SB Admin 2 theme, applied ONLY to the admin
   shell (.pbadmin). The storefront never receives these rules.
   Nunito font is loaded via index.html (used only in admin).
   ============================================================ */
${finalCss}
`
writeFileSync(OUT, out)
console.log(`scoped ${IN} → ${OUT} (${(out.length / 1024).toFixed(1)} KB)`)
